on:
  push: 
  workflow_dispatch:
  #schedule:
  #  - cron: '0 * * * *' # run at 2 AM UTC
jobs:
  ticket:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: setup node
        uses: actions/setup-node@v4

      - name: Installing package list
        run: apt list --installed
      - name: Removing previous chrome instances on runner
        run: sudo apt purge google-chrome-stable

       # Need to fetch reqs if needed
      - name: Installing all necessary packages
        run: pip install chromedriver-autoinstaller selenium pyvirtualdisplay

      - name: Install xvfb
        run: sudo apt-get install xvfb

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script
        run: |
          python fetch.py \
            --from-url "https://www.bahn.de/buchung/start?vbid=d72a6bff%2Dc003%2D4d29%2D9c60%2D06c88d4a3f5e" \
            --to-url "https://www.bahn.de/buchung/start?vbid=d72a6bff%2Dc003%2D4d29%2D9c60%2D06c88d4a3f5e" \
            --name april2025 \
            --discount 25

      - name: push
        if: always()
        env:
          CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
          CI_COMMIT_AUTHOR: Continuous Integration
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "username@users.noreply.github.com"
          tree
          git add data/* || echo ""
          git status || echo ""
          git commit -m "${{ env.CI_COMMIT_MESSAGE }}" || echo ""
          git push || echo ""