on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC
jobs:
  ticket:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script
        #env:
        #  SOME_SECRET: ${{ secrets.SOME_SECRET }}
        run: python ticket.py

      - name: execute py script
        #env:
        #  SOME_SECRET: ${{ secrets.SOME_SECRET }}
        run: python chart.py

      - name: push
        if: always()
        env:
          CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
          CI_COMMIT_AUTHOR: Continuous Integration
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "username@users.noreply.github.com"
          tree
          git add Bilder/*.png || echo ""
          git add sampledata.png || echo ""
          git add ticket_prices.csv || echo ""
          git status || echo ""
          git commit -m "${{ env.CI_COMMIT_MESSAGE }}" || echo ""
          git push || echo ""