on:
  push: 
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'
jobs:
  ticket:
    permissions:
      contents: write
      issues: write
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install German locale
        run: |
          sudo apt-get update
          sudo apt-get install -y locales
          sudo locale-gen de_DE.UTF-8
          sudo update-locale LANG=de_DE.UTF-8

      - name: setup node
        uses: actions/setup-node@v4

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script
        run: |
          python ticket.py 
          python chart.py

      - name: push
        if: always()
        env:
          CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
          CI_COMMIT_AUTHOR: Continuous Integration
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "username@users.noreply.github.com"
          tree
          git add * || echo ""
          git status || echo ""
          git commit -m "${{ env.CI_COMMIT_MESSAGE }}" || echo ""
          git push || echo ""

      - name: issue
        run: |
          
          if awk -F, 'NR > 1 {prev2 = col2; prev3 = col3} {col2 = $2; col3 = $3} END {exit !(col2 < prev2 || col3 < prev3)}' "ticket_prices.csv"; then
              echo "Condition not met: Last row values are not lower."
          else
              gh issue create \
                --title "$TITLE" \
                --assignee "$ASSIGNEES" \
                --body "
                  ## Korn Alarm
                  Folgende Preisminderung wurde festgesgellt:
                  `tail -n 2 ticket_prices.csv`
                "
          fi

        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          TITLE: Kornalarm
          ASSIGNEES: maxgruber19,Chrish-97
