on:
  push: 
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'
jobs:
  ticket:
    permissions:
      contents: write
      issues: write
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install German locale
        run: |
          sudo apt-get update
          sudo apt-get install -y locales
          sudo locale-gen de_DE.UTF-8
          sudo update-locale LANG=de_DE.UTF-8

      - name: setup node
        uses: actions/setup-node@v4

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script
        run: |
          python ticket.py 
          python chart.py

      - name: push
        if: always()
        env:
          CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
          CI_COMMIT_AUTHOR: Continuous Integration
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "username@users.noreply.github.com"
          tree
          git add * || echo ""
          git status || echo ""
          git commit -m "${{ env.CI_COMMIT_MESSAGE }}" || echo ""
          git push || echo ""

      - name: issue
        run: |
          
          # Extract the last two rows
          last_two_rows=$(tail -2 "ticket_prices.csv")
          
          # Read values from the last two rows
          read -r ts1 col2_prev col3_prev <<<"$(echo "$last_two_rows" | head -1 | awk -F, '{print $1, $2, $3}')"
          read -r ts2 col2_last col3_last <<<"$(echo "$last_two_rows" | tail -1 | awk -F, '{print $1, $2, $3}')"
          
          # Compare values
          if (( $(echo "$col2_last < $col2_prev" | bc -l) )) || (( $(echo "$col3_last < $col3_prev" | bc -l) )); then
              gh issue create \
                --title "Preissenkung" \
                --assignee "$ASSIGNEES" \
                --body "# Preisminderung
                '''
                $last_two_rows
                '''
                "
          elif (( $(echo "$col2_last > $col2_prev" | bc -l) )) || (( $(echo "$col3_last > $col3_prev" | bc -l) )); then
              gh issue create \
                --title "Preiserhöhung" \
                --assignee "$ASSIGNEES" \
                --body "# Preiserhöhung
                '''
                $last_two_rows
                '''
                "
          else
              echo "no change"
          fi

        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          TITLE: Kornalarm
          ASSIGNEES: maxgruber19,Chrish-97
